# Generated by Django 2.0.3 on 2018-04-14 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0003_auto_20180319_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='esAcreedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apunte',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='vehiculoKm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Km.Vehiculo'),
        ),
    ]
